### ID of the AWS account where your cluster is located
awsAccountID:
### Name of your EKS cluster; it is used as:
### * a postfix in your IAM role's and policy's names, for example 'k8s-testapp-cluster1'
### * a tag for your IAM role and policy, 'cluster_name: cluster1'
clusterName:
### AWS OpenID Connect hostname of your EKS cluster (unique for each cluster)
oidc:
### Prefix that will be added to each IAM policy and IAM role created by this controller on AWS, must end with a separator supported by AWS, such as '-', or '_'
iamNamePrefix: "k8s-"
### ARN of a Permissions Boundary IAM policy to be attached to all IAM roles under '.Values.irsa'; conflicts with '.Values.irsa[*].permissionsBoundary'
iamRolePermissionsBoundary: ""

### Describe your IAM role and policy below
irsa: []
#  - name: <Name of your application, string>
#    serviceAccountName: <Name of the K8s ServiceAccount, string>
#    doNotCreateServiceAccount: <Set to true if you don't need a K8s SA object to be created (defaults to - false), boolean>
#    description: <Description that will be added to both IAM role and IAM policy on AWS, string»
#    permissionsBoundary: <ARN of a Permissions Boundary IAM policy to be attached to this IAM role (conflicts with '.Values.iamRolePermissionsBoundary'), string>
#    policies:
#      - name: <policy name, string>
#        policyDocumentYAML:
#          Version: "2012-10-17"
#          Statement:
#            - Sid: <Name of the policy statement, string>
#              Effect: "Effect, string, Allow/Deny"
#              Action:
#                - "<Name of an AWS API>:<Action>"
#              Resource: ["*"]
#    maxSessionDuration: <Maximum duration of a session in seconds, int>

### These tags will be added to each IAM policy and IAM role created by this controller on AWS
common_tags:
  - key: managed_by
    value: eks
  - key: controller
    value: ack-iam-controller

### These tags will be added to each IAM policy and IAM role created by this controller on AWS
custom_tags: []
